version: '3.4'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest-conexa-challenger
    ports:
      - "3308:3306"
    networks:
      - conexa-network

  rest-conexa-challenger:
    image: rest-conexa-challenger
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # working_dir: /app
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - conexa-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - conexa-network
networks:
  conexa-network:
    driver: bridge