version: "3.9"

services:
  desafio-app:
    container_name: desafio-app
    image: desafio-img
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/desafio/src/
    networks:
      - desafio-mysql
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0.32
    networks:
      - desafio-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=desafio_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5

networks:
  desafio-mysql: