version: '3'

services:
  mysql-db:
    image: mysql:8.0.35
    container_name: container-schedulingappoinment
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: schedulingappoinment
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
